version: '2'
services:
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret
      - MYSQL_DATABASE=store
      - MYSQL_USER=store-user
      - MYSQL_PASSWORD=store-secret
